version: '3'
services:
  streamlit_app:
    build: .
    ports:
      - "8888:8888"
      - "8501:8501"
    volumes:
      - "./app:/app"
      - "./src:/src"

    command:  nohup streamlit run ./app/streamlit_app.py

